-- TOTAL SALES FOR EACH MONTH AND RUNNING TOTAL SALES OVER TIME
SELECT 
	DATE
	,TOTAL_SALES
	,SUM(TOTAL_SALES) OVER(PARTITION BY DATEPART(YEAR,DATE) ORDER BY DATE DESC) AS RUNNING_TOTAL
FROM (
	SELECT 
		DATETRUNC(MONTH,order_date) AS DATE
		,SUM(sales_amount) AS TOTAL_SALES
	FROM gold.fact_sales
	GROUP BY  DATETRUNC(MONTH,order_date)
)T
WHERE DATE IS NOT NULL;
