-- exploring DATA BASE 
-- all the object of the data base 

SELECT 
* 
FROM INFORMATION_SCHEMA.TABLES

-- information about all the columns inside our database
SELECT 
* 
FROM INFORMATION_SCHEMA.COLUMNS

-- exploring all the columns inside the table gold.dim_customer

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customer'

-- exploring all the country our costomers come from 

SELECT DISTINCT
	country
FROM gold.dim_customer


-- exploring all the catorgaries from the product 

SELECT DISTINCT
	product_catogary
	,subcatogary
	,product_name
FROM gold.dim_products
--WHERE product_catogary IS NOT NULL
ORDER BY 1,2,3


-- DATE EXPLORATION 
-- finding the date of the first and the last order 
-- AND the order range in years 

SELECT 
MIN(order_date) AS first_order
,MAX(order_date) AS last_order
,DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS order_range_years
FROM gold.fact_sales

-- youngest and oldest customer 

SELECT
MIN(birthdate) AS oldest_customer_birthdate
,DATEDIFF(YEAR,MIN(birthdate),GETDATE()) AS age_of_oldest
,MAX(birthdate) AS youngest_customer_birthdate
,DATEDIFF(YEAR,MAX(birthdate),GETDATE()) AS age_of_youngest
FROM gold.dim_customer

--exploring masures 

--find the total number of sales 

SELECT 
		FORMAT (SUM(sales_amount),'N') AS TOTAL SALES
FROM gold.fact_sales

-- find how many items were sold 

SELECT 
	SUM(quantity) AS total_item_sold
FROM gold.fact_sales

--find the average selling price

SELECT
	AVG(price) AS avrage_price
FROM gold.fact_sales

--find total numbers of orders

SELECT 
	COUNT(order_number) AS TOTAL_ORDERS
FROM gold.fact_sales ;
--UNIQUE ORDERS 
SELECT 
	COUNT(DISTINCT order_number) AS TOTAL_ORDERS
FROM gold.fact_sales;

-- FIND TOTAL NUBMERS OF PRODUCTS 
SELECT 
	count (DISTINCT product_name) 
FROM gold.dim_products;

SELECT 
	COUNT(DISTINCT product_number)
FROM gold.dim_products;

-- find the total numbers of customers 

SELECT
	COUNT(DISTINCT customer_key)
FROM gold.dim_customer


-- find the total number of customer who placed order id 

SELECT 
	count(DISTINCT customer_key)
FROM gold.fact_sales 

----------------------------
--FINAL REPORT 

SELECT 
	'TOTAL SALES' AS [MASURE NAME]
	,SUM(sales_amount) AS [MASURE VALUE]
FROM gold.fact_sales
UNION ALL
SELECT 
	'TOTAL_QUANTITY'
	,SUM(quantity)
FROM gold.fact_sales
UNION ALL 
SELECT
	'AVRAGE_PRICE'
	,AVG(price)
FROM gold.fact_sales
UNION ALL
SELECT 
	'TOTAL_ORDERS'
	,COUNT(DISTINCT order_number)
FROM gold.fact_sales
UNION ALL
SELECT 
	'TOTAL_PRODUCTS'
	,COUNT(DISTINCT product_number)
FROM gold.dim_products
UNION ALL
SELECT 
	'TOTAL_CUSTOMERS'
	,COUNT(DISTINCT customer_key)
FROM gold.dim_customer
;

--FIND TOTAL CUSTOMER BY COUNTRIES

SELECT 
	 country
	,COUNT(customer_key) AS total_customers
FROM gold.dim_customer
GROUP BY country
ORDER BY 2 DESC;
--FIND total customers by gender
SELECT 
	 Gender
	,COUNT(customer_key) AS total_customers
FROM gold.dim_customer
GROUP BY Gender
ORDER BY 2 DESC;

--find total product by accesories

SELECT 
	product_catogary
	,COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY  product_catogary
ORDER BY 2 DESC;

--find average cost each catogary

SELECT 
	product_catogary
	,AVG(product_cost) AS avarage_cost
FROM gold.dim_products
WHERE product_catogary IS NOT NULL
GROUP BY product_catogary
ORDER BY 2 DESC;

-- find total revenue by each catogary 
SELECT 
	p.product_catogary
	,SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON s.product_key = p.product_key
GROUP BY p.product_catogary
ORDER BY 2 DESC;

-- WHAT IS THE TOTAL REVENUE GENERATED BY EACH CUSTOMER 

SELECT 
	c.customer_key
	,c.first_name
	,c.last_name
	,SUM(s.sales_amount) AS total_salea
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customer AS c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name,c.last_name
ORDER BY 4 DESC

-- total sold items by country

SELECT 
	c.country
	,SUM(quantity) AS total_item_sold
FROM gold.fact_sales AS s 
LEFT JOIN gold.dim_customer AS c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY 2 DESC;

-- RANK TOP 5 PRODUCT GENERATED HIGHEST REVENUE 

SELECT  TOP 5
	p.product_name 
	,SUM(s.sales_amount) AS TOTAL_SALES 
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY 2 DESC ;

-- RANK TOP 5 PRODUCT THAT GENERATED LOWEST REVENUE

SELECT TOP 5
	p.product_name
	,SUM(s.sales_amount) AS  TOTAL_SALES
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY 2 

-- top ten highest revenue by customers 
SELECT TOP 10
	c.customer_key
	,c.first_name
	,c.last_name
	,SUM(s.sales_amount) AS total_salea
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customer AS c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name,c.last_name
ORDER BY 4 DESC

-- TOP 3 CUSTOMERS WITH FEWEST ITEM

SELECT TOP 3
	c.customer_key
	,c.first_name
	,c.last_name
	,COUNT(DISTINCT s.order_number) AS total_ORDERS
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customer AS c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name,c.last_name
ORDER BY 4 
